apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-prod-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: pre-prod
  template:
    metadata:
      labels:
        app: pre-prod
    spec:
      containers:
      - name: redis-container
        image: redis

